name: Build Egg

on:
  push:
    branches: [ '3.0_egg']
  pull_request:
    branches: [ '3.0_egg']

jobs:
  build-egg:

    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get install -y --no-install-recommends python3 git zip
    - uses: actions/checkout@v4
    - name: Build egg
      run: |
        ./build_client_egg.sh python3
    - name: Upload egg
      uses: actions/upload-artifact@v4
      with:
        name: egg
        path: insights.zip
        retention-days: 7
